//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TF.WIN.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TF.WIN.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap actividad_muscular_grupo_B {
            get {
                object obj = ResourceManager.GetObject("actividad muscular grupo B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap analisis_brazo {
            get {
                object obj = ResourceManager.GetObject("analisis brazo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap antebrazo {
            get {
                object obj = ResourceManager.GetObject("antebrazo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CARGA_FUERZA_GRUPO_B {
            get {
                object obj = ResourceManager.GetObject("CARGA FUERZA GRUPO B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] CarpetaIntegradoraAdmProy1 {
            get {
                object obj = ResourceManager.GetObject("CarpetaIntegradoraAdmProy1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ergo {
            get {
                object obj = ResourceManager.GetObject("ergo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] ManualdeUsuario {
            get {
                object obj = ResourceManager.GetObject("ManualdeUsuario", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///    &lt;table style=&quot;width: 100%;&quot;&gt;
        ///
        ///        &lt;tr&gt;
        ///            &lt;td style=&quot;width: 35%;&quot;&gt;&lt;/td&gt;
        ///            &lt;td style=&quot;width: 60%;&quot; align=&quot;center&quot;&gt;
        ///                &lt;table&gt;
        ///                    &lt;tr&gt;&lt;td align=&quot;center&quot;&gt;ERGOASIST&lt;/td&gt;&lt;/tr&gt;
        ///                    &lt;tr&gt;&lt;td align=&quot;center&quot;&gt;AV. COLON 1250&lt;/td&gt;&lt;/tr&gt;
        ///                    &lt;tr&gt;&lt;td align=&quot;center&quot;&gt;TEL: 3513091777&lt;/td&gt;&lt;/tr&gt;
        ///                &lt;/table&gt;
        ///            &lt;/td&gt;
        ///            &lt;td style=&quot;width: 35%;&quot;&gt;
        ///  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string planilla1 {
            get {
                return ResourceManager.GetString("planilla1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///    &lt;table style=&quot;width: 100%;&quot;&gt;
        ///
        ///        &lt;tr&gt;
        ///            &lt;td style=&quot;width: 35%;&quot;&gt;&lt;/td&gt;
        ///            &lt;td style=&quot;width: 60%;&quot; align=&quot;center&quot;&gt;
        ///                &lt;table&gt;
        ///                    &lt;tr&gt;&lt;td align=&quot;center&quot;&gt;ERGOASIST&lt;/td&gt;&lt;/tr&gt;
        ///                    &lt;tr&gt;&lt;td align=&quot;center&quot;&gt;AV. COLON 1250&lt;/td&gt;&lt;/tr&gt;
        ///                    &lt;tr&gt;&lt;td align=&quot;center&quot;&gt;TEL: 3513091777&lt;/td&gt;&lt;/tr&gt;
        ///                &lt;/table&gt;
        ///            &lt;/td&gt;
        ///            &lt;td style=&quot;width: 35%;&quot;&gt;
        ///  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string plantilla {
            get {
                return ResourceManager.GetString("plantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///    &lt;table style=&quot;width: 100%;&quot;&gt;
        ///
        ///        &lt;tr&gt;
        ///            &lt;td style=&quot;width: 35%;&quot;&gt;&lt;/td&gt;
        ///            &lt;td style=&quot;width: 60%;&quot; align=&quot;center&quot;&gt;
        ///                &lt;table&gt;
        ///                    &lt;tr&gt;&lt;td align=&quot;center&quot;&gt;ERGOASIST&lt;/td&gt;&lt;/tr&gt;
        ///                    &lt;tr&gt;&lt;td align=&quot;center&quot;&gt;AV. COLON 1250&lt;/td&gt;&lt;/tr&gt;
        ///                    &lt;tr&gt;&lt;td align=&quot;center&quot;&gt;TEL: 3513091777&lt;/td&gt;&lt;/tr&gt;
        ///                &lt;/table&gt;
        ///            &lt;/td&gt;
        ///            &lt;td style=&quot;width: 35%;&quot;&gt;
        ///  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string plantilla2 {
            get {
                return ResourceManager.GetString("plantilla2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///    &lt;table style=&quot;width: 100%;&quot;&gt;
        ///
        ///        &lt;tr&gt;
        ///            &lt;td style=&quot;width: 35%;&quot;&gt;&lt;/td&gt;
        ///            &lt;td style=&quot;width: 60%;&quot; align=&quot;center&quot;&gt;
        ///                &lt;table&gt;
        ///                    &lt;tr&gt;&lt;td align=&quot;center&quot;&gt;ERGOASIST&lt;/td&gt;&lt;/tr&gt;
        ///                    &lt;tr&gt;&lt;td align=&quot;center&quot;&gt;AV. COLON 1250&lt;/td&gt;&lt;/tr&gt;
        ///                    &lt;tr&gt;&lt;td align=&quot;center&quot;&gt;TEL: 3513091777&lt;/td&gt;&lt;/tr&gt;
        ///                &lt;/table&gt;
        ///            &lt;/td&gt;
        ///            &lt;td style=&quot;width: 35%;&quot;&gt;
        ///  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string plantilla3 {
            get {
                return ResourceManager.GetString("plantilla3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///    &lt;table style=&quot;width: 100%;&quot;&gt;
        ///
        ///        &lt;tr&gt;
        ///            &lt;td style=&quot;width: 35%;&quot;&gt;&lt;/td&gt;
        ///            &lt;td style=&quot;width: 60%;&quot; align=&quot;center&quot;&gt;
        ///                &lt;table&gt;
        ///                    &lt;tr&gt;&lt;td align=&quot;center&quot;&gt;ERGOASIST&lt;/td&gt;&lt;/tr&gt;
        ///                    &lt;tr&gt;&lt;td align=&quot;center&quot;&gt;AV. COLON 1250&lt;/td&gt;&lt;/tr&gt;
        ///                    &lt;tr&gt;&lt;td align=&quot;center&quot;&gt;TEL: 3513091777&lt;/td&gt;&lt;/tr&gt;
        ///                &lt;/table&gt;
        ///            &lt;/td&gt;
        ///            &lt;td style=&quot;width: 35%;&quot;&gt;
        ///  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string plantillaconsultaPuestosEmpleado {
            get {
                return ResourceManager.GetString("plantillaconsultaPuestosEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] ProductoSistema {
            get {
                object obj = ResourceManager.GetObject("ProductoSistema", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap puntuacion_carga_fuerza {
            get {
                object obj = ResourceManager.GetObject("puntuacion carga fuerza", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap puntuacion_del_cuello {
            get {
                object obj = ResourceManager.GetObject("puntuacion del cuello", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap puntuacion_giro_muneca {
            get {
                object obj = ResourceManager.GetObject("puntuacion giro muneca", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap puntuacion_muneca {
            get {
                object obj = ResourceManager.GetObject("puntuacion muneca", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap puntuacion_pierna {
            get {
                object obj = ResourceManager.GetObject("puntuacion pierna", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap puntuacion_tipo_de_actividad_manual {
            get {
                object obj = ResourceManager.GetObject("puntuacion tipo de actividad manual", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap puntuacion_tronco {
            get {
                object obj = ResourceManager.GetObject("puntuacion tronco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] TesteoSistema {
            get {
                object obj = ResourceManager.GetObject("TesteoSistema", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
